#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class V1beta1_VolumeSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            
            'emptyDir': 'V1beta1_EmptyDirVolumeSource',
            
            
            'gitRepo': 'V1beta1_GitRepoVolumeSource',
            
            
            'hostDir': 'V1beta1_HostPathVolumeSource',
            
            
            'persistentDisk': 'V1beta1_GCEPersistentDiskVolumeSource',
            
            
            'secret': 'V1beta1_SecretVolumeSource'
            
        }

        
        #temporary directory that shares a pod&#39;s lifetime
        
        self.emptyDir = None # V1beta1_EmptyDirVolumeSource
        
        #git repository at a particular revision
        
        self.gitRepo = None # V1beta1_GitRepoVolumeSource
        
        #pre-existing host file or directory; generally for privileged system daemons or other agents tied to the host
        
        self.hostDir = None # V1beta1_HostPathVolumeSource
        
        #GCE disk resource attached to the host machine on demand
        
        self.persistentDisk = None # V1beta1_GCEPersistentDiskVolumeSource
        
        #secret to populate volume with
        
        self.secret = None # V1beta1_SecretVolumeSource
        
