#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class V1beta1_VolumeMount(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            
            'mountPath': 'str',
            
            
            'mountType': 'str',
            
            
            'name': 'str',
            
            
            'path': 'str',
            
            
            'readOnly': 'bool'
            
        }

        
        #path within the container at which the volume should be mounted; overrides path
        
        self.mountPath = None # str
        
        #LOCAL or HOST; defaults to LOCAL; deprecated
        
        self.mountType = None # str
        
        #name of the volume to mount
        
        self.name = None # str
        
        #path within the container at which the volume should be mounted; deprecated
        
        self.path = None # str
        
        #mounted read-only if true, read-write otherwise (false or unspecified)
        
        self.readOnly = None # bool
        
