#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class V1beta1_ReplicationControllerState(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            
            'podTemplate': 'V1beta1_PodTemplate',
            
            
            'replicaSelector': 'V1beta1_ReplicationControllerState_replicaSelector',
            
            
            'replicas': 'int'
            
        }

        
        #template for pods to be created by this replication controller when the observed number of replicas is less than the desired number of replicas
        
        self.podTemplate = None # V1beta1_PodTemplate
        
        #label keys and values that must match in order to be controlled by this replication controller
        
        self.replicaSelector = None # V1beta1_ReplicationControllerState_replicaSelector
        
        #number of replicas (desired or observed, as appropriate)
        
        self.replicas = None # int
        
