#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class V1beta1_PodState(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            
            'Condition': 'list[V1beta1_PodCondition]',
            
            
            'host': 'str',
            
            
            'hostIP': 'str',
            
            
            'info': 'V1beta1_PodInfo',
            
            
            'manifest': 'V1beta1_ContainerManifest',
            
            
            'message': 'str',
            
            
            'podIP': 'str',
            
            
            'status': 'V1beta1_PodStatus'
            
        }

        
        #current service state of pod
        
        self.Condition = None # list[V1beta1_PodCondition]
        
        #host to which the pod is assigned; empty if not yet scheduled; cannot be updated
        
        self.host = None # str
        
        #IP address of the host to which the pod is assigned; empty if not yet scheduled
        
        self.hostIP = None # str
        
        #map of container name to container status
        
        self.info = None # V1beta1_PodInfo
        
        #manifest of containers and volumes comprising the pod
        
        self.manifest = None # V1beta1_ContainerManifest
        
        #human readable message indicating details about why the pod is in this condition
        
        self.message = None # str
        
        #IP address allocated to the pod; routable at least within the cluster; empty if not yet allocated
        
        self.podIP = None # str
        
        #current condition of the pod, Waiting, Running, or Terminated
        
        self.status = None # V1beta1_PodStatus
        
