#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class V1beta1_NodeStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            
            'addresses': 'list[V1beta1_NodeAddress]',
            
            
            'conditions': 'list[V1beta1_NodeCondition]',
            
            
            'nodeInfo': 'V1beta1_NodeSystemInfo',
            
            
            'phase': 'V1beta1_NodePhase'
            
        }

        
        #list of addresses reachable to the node
        
        self.addresses = None # list[V1beta1_NodeAddress]
        
        #conditions is an array of current node conditions
        
        self.conditions = None # list[V1beta1_NodeCondition]
        
        #node identity is a set of ids/uuids to uniquely identify the node
        
        self.nodeInfo = None # V1beta1_NodeSystemInfo
        
        #node phase is the current lifecycle phase of the node
        
        self.phase = None # V1beta1_NodePhase
        
