demand-listeners:
    - name: gearman-server
      type: gearman
      host: xx.xx.xx.xx
      port: 4730

destroy-listeners:
    - name: zmq
      type: zmq
      host: xx.xx.xx.xx
      port: 8888

jenkins:
    url: 'http://xx.xx.xx.xx'
    user: jenkins
    pass: jenkins
kubernetes:
    url: 'http://xx.xx.xx.xx:8080'
    api_key: key
image: yrobla/jenkins-slave-swarm-infra:latest
